config/routes.rb
Treashery::Application.routes.draw do
  match "faq" => "pages#faq", :as => :faq
  match "about" => "pages#about", :as => :about
  match "contact" => "pages#contact", :as => :contact

  resources :localities, only: [:show, :search] do
    get 'search', on: :collection
  end

  resources :spots
  root :to => 'spots#index'
end

app/models/address_component.rb
class AddressComponent
  include Mongoid::Document

  field :long_name, type: String
  field :short_name, type: String
  field :types, type: Array

  embedded_in :locality, inverse_of: :address_components
end

app/models/geometry.rb
class Geometry
  include Mongoid::Document

  field :location, type: Point
  field :location_type, type: String
  field :viewport, type: Viewport
end

app/models/locality.rb
class Locality
  include Mongoid::Document

  field :formatted_address, type: String
  field :types, type: Array, default: []

  embeds_many :address_components, class_name: 'AddressComponent'
  embeds_one :geometry

  validates :formatted_address, :types, :geometry, presence: true
  belongs_to :locality
  has_many :localities

  validates_uniqueness_of :formatted_address, scope: [:types]

  scope :search,  ->(search) {where(:"address_components.long_name" => search)}

  def find_best_parent(localities_array)
    localities_array.min do |a,b|
      (self.address_components.map(&:short_name) - a.address_components.map(&:short_name)).size <=> (self.address_components.map(&:short_name) - b.address_components.map(&:short_name)).size
    end
  end
end

app/models/point.rb
class Point
  include Mongoid::Document

  field :lat, type: Float
  field :lng, type: Float
end

app/models/spot.rb
class Spot
  include Mongoid::Document
  include Geocoder::Model::Mongoid

  embeds_one :location, class_name: 'Point'
  accepts_nested_attributes_for :location
  field :coordinates, type: Array
  index [[ :coordinates, Mongo::GEO2D ]], min: -180, max: 180

  field :name, type: String
  field :description, type: String
  field :type, type: String

  before_save :set_coordinates
  before_save :reverse_geocode
  has_many :localities

  validates :name, :type, presence: true
  paginates_per 10

  TYPES = %w(medical electronic animal_prod radioactive food other)

  scope :bounded, ->(swLng, swLat, neLng, neLat) {
    if swLng.present? && swLat.present? && neLng.present? && neLat.present?
      where(:coordinates.within => {"$box" => [[swLng.to_f, swLat.to_f], [neLng.to_f, neLat.to_f]]})
    else
      all
    end
  }

  scope :typed, ->(type) {
    if type.present?
      where(:type => type)
    else  
      all
    end
  }

  def set_coordinates
    self.coordinates = [location.lng, location.lat]
  end

  def reverse_geocode
    possible_parents = []
    Geocoder.search(coordinates).reverse.each do |result|
      locality = Locality.create(result.data)
      if locality.persisted?
        locality.update_attributes(locality: locality.find_best_parent(possible_parents))
      else
        locality = Locality.any_in('address_components.short_name' => result.address_components.map{|ac| ac['short_name']}).first
      end
      possible_parents << locality
    end
    self.localities = possible_parents.compact
  end
end

app/models/viewport.rb
class Viewport
  include Mongoid::Document

  field :southwest, type: Point
  field :northeast, type: Point

  validates :southwest, :northeast, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  def show
    @locality = Locality.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @locality }
    end
  end

  def search
    @locality = Locality.search(params[:search]).first

    respond_to do |format|
      format.html
      format.json { render json: @locality }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def about
  end

  def contact
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots = Spot.bounded(params[:swLng], params[:swLat], params[:neLng], params[:neLat]).typed(params[:type])

    respond_to do |format|
      format.html { @spots = @spots.page(params[:page])}
      format.json { render json: @spots }
      format.js { @spots = @spots.page(params[:page])}
    end
  end

  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @spot }
      format.js
    end
  end

  def new
    @spot = Spot.new
    @spot.build_location(lat: params[:lat], lng: params[:lng])

    respond_to do |format|
      format.html
      format.json { render json: @spot }
      format.js
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def create
    @spot = Spot.new(params[:spot])
    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :ok }
      format.js
    end
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title Treashery
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .links
      - Spot::TYPES.each do |type|
        %span{:class => type}= link_to type, '#', id: type, class: "spot_type #{type}", :'data-type' => type
        \|
      %span{:class => "all"}= link_to "all", '#', id: 'all', class: 'spot_type all selected', :'data-type' => ""
    #type{ :'data-type' => "" }
    #header
      #title
        %h1 Welcome to Treashery
      #search
        = form_tag url_for(:action => 'search', :controller => 'localities', format: :json), id: 'searchForm', method: :get, remote: true
        = text_field_tag 'search', nil, placeholder: 'Enter search term...', id: 'searchInput'
        = submit_tag 'Search'
      .links
        = link_to "Home", root_path
        \|
        = link_to "Faq", faq_path
        \|
        = link_to "About", about_path
        \|
        = link_to "Contact", contact_path

    = yield

    #footer
      %p trashery.com 2011

app/views/localities/show.html.haml
= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.4&?libraries=geometry&sensor=false"

%p#notice= notice

%p
  %b Address:
  = @locality.formatted_address
%p
  %b Types:
  %ul
  - @locality.types.each do |type|
    %li= type

app/views/pages/about.html.haml
%h1 Welcome to Treashery.com!
%p
  If you are here it means, that you found some stinky garbage laying on the street, or maybe forest?
%p
  You are right! We have to show people that only idiots are storing their shit on streets! =P
%p
  Good luck and have fun with adding new spots and uploading photos :)

app/views/pages/contact.html.haml
%p
  Contact with administrators: blablablabla@gmail.com

app/views/pages/faq.html.haml
%h1 Lorem ipsum!
%p
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec arcu ligula, ultricies sit amet dapibus quis, congue nec eros. Nullam luctus, justo ac placerat adipiscing, massa mauris bibendum nunc, quis euismod erat dolor id sem. Phasellus rhoncus hendrerit viverra. Curabitur odio sem, congue id fermentum nec, aliquam in massa. Aenean porta, purus et aliquet pulvinar, turpis sem porttitor leo, malesuada sollicitudin lorem tortor vitae augue. Duis dignissim nisl ut elit semper dapibus. Donec lacinia viverra nulla, in condimentum quam porta lacinia. Praesent id ipsum eget risus faucibus dignissim sit amet sit amet ligula. Aliquam ipsum justo, laoreet semper hendrerit at, ultrices a tellus. Ut non mollis neque. Nullam tincidunt facilisis nibh, at pharetra nunc euismod et. Donec consectetur hendrerit quam vel sodales. Sed ac volutpat metus. Morbi in nisi ut tellus imperdiet bibendum nec at lacus. Maecenas elementum luctus nisl, ac pretium leo vestibulum non. Sed ornare massa et tellus varius suscipit. Duis accumsan interdum tellus, ut luctus nisl ornare at. Curabitur vehicula pharetra felis ac interdum.

app/views/spots/_form.html.haml
= simple_form_for @spot do |f|
  -if @spot.errors.any?
    #error_explanation
      %h2= "#{pluralize(@spot.errors.count, "error")} prohibited this spot from being saved:"
      %ul
        - @spot.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name
  = f.simple_fields_for :location do |location_form|
    = location_form.input :lat
    = location_form.input :lng
  = f.input :type, collection: Spot::TYPES
  = f.input :description, as: :text
  = f.button :submit

app/views/spots/_spot.html.haml
.spot.vcard
  = link_to spot.name, spot, class: 'fn url'
  .geo.hidden
    .latitude
      = spot.location.lat
    .longitude
      = spot.location.lng
  .type
    = spot.type

app/views/spots/edit.html.haml
= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.4&?libraries=geometry&sensor=false"
%h1 Editing spot

= render 'form'

= link_to 'Show', @spot
\|
= link_to 'Back', spots_path

app/views/spots/index.html.haml
= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.4&?libraries=geometry&sensor=false"

#map_content
  #google_map
#sidebar
  %h3 Spot list:
  #spotlist
    = render @spots
  #paginator
    = paginate @spots, :remote => true
#add_new_spot
  %p= link_to 'New Spot', new_spot_path

app/views/spots/index.js.erb
$("#spotlist").html("<%= escape_javascript(render @spots) %>");
$("#paginator").html("<%= escape_javascript(paginate(@spots, :remote => true).to_s) %>");
deleteMarkers();
addAllMarkers();

app/views/spots/new.html.haml
= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.4&?libraries=geometry&sensor=false"
%h1 New spot

= render 'form'

= link_to 'Back', root_url

app/views/spots/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @spot.name
%p
  %b Lat:
  = @spot.location.lat
%p
  %b Lng:
  = @spot.location.lng
%p
  %b Type:
  = @spot.type
%p
  %b Description:
  = @spot.description

= link_to 'Edit', edit_spot_path(@spot)
\|
= link_to 'Destroy', @spot, :confirm => 'Are you sure?', :method => :delete
\|
= link_to 'Back', root_url